WINDOW_WIDTH = 800
WINDOW_HEIGHT = 400
OBSTACLE_SIZE = 100
fps = 30
V = 30
V_delta = 10
R = 30
LEVEL_COUNT = 3
W = 50  # разница между центром круга и координатой, откуда должен начинаться отсчет для динозавтра
COIN_SIZE = 20